[build]
publish = "dist"
command = """
  curl -s --retry 5 --retry-all-errors https://api.github.com/repos/elanthia-online/jinxp/releases/latest \
  | grep browser_download_url \
  | grep jinxp \
  | cut -d '"' -f 4 \
  | wget --tries=5 --retry-conrefused --retry-on-host-error -qi - \
  && chmod +x jinxp \
  && ./jinxp -i lib
  """
