[build]
publish = "dist"
command = """
  curl -s https://api.github.com/repos/elanthia-online/jinxp/releases/latest \
  | grep browser_download_url \
  | grep jinxp \
  | cut -d '"' -f 4 \
  | wget -qi - \
  && chmod +x jinxp \
  && ./jinxp -i lib
  """