=begin
	This file required in order for flaretracker_2.lic to function.
	
	1.0.0 (2024-09-7)
		- Initial release of flare patterns global constants.
		- 88 different flare patterns added.
=end

# Define FLARE_PATTERNS as a constant to be used globally
FLARE_PATTERNS = {
  Acid_Flare: /\*\* Your .* releases? a spray of acid! \*\*/,
  Acuity_Flare: /Your .* glows intensely with a verdant light!/,
  Adamantine: /the incredibly hard surface of your adamantine/,
  Air_Flare: /\*\* Your .* unleashes? a blast of air! \*\*/,
  Air_LoreFlare: /A fierce whirlwind erupts? around .* encircling .* in a suffocating cyclone/,
  Air_LoreFlareDoT: /The cyclone whirls around .* anew/,
  Air_GEF: /\*\* A howling gale of steaming air rushes from .*/,
  Animalistic_FuryFlares: /slender tendrils rising up to coalesce into the ethereal form of/,
  Animalistic_InstinctFlares: /up from the point of impact, spreading over the chest of your/,
  Animalistic_Totem: /flows from it and over your exposed skin, imbuing a sudden rush of power from/,
  Bestial_Totem: /the semitransparent figure moving to try to shield you from the attack/,
  Shifting_Totem: /the motes encasing your arm in incandescence as a rush of power sinks into you to strengthen your attack/,
  Feral_Totem: /totem/,
  Blink: /Your .* suddenly lights? up with hundreds of tiny blue sparks/,
  Briar: /Vines of vicious briars whip out from your/,
  Bubble: /high-pitched sound and causes your skin and muscles to/,
  Cold_Flare: /\*\* Your .* glows? intensely with a cold blue light! \*\*/,
  Cold_GEF: /\*\* A vortex of razor-sharp ice gusts from .* and coalesces? around a .*! \*\*/,
  Disintegration_Flare: /\*\* Your .* releases? a shimmering beam of disintegration! \*\*/,
  Dispel_Flare: /\*\* Your .* glows? brightly for a moment, consuming the magical energies around .*!/,
  Disruption_Flare: /\*\* Your .* releases? a quivering wave of disruption! \*\*/,
  Dramatic_Drapery_Masquerade: /distorts the air around you, confounding an/,
  Dramatic_Drapery_Wondorous: /Branching filaments of power snap outward from your/,
  Earth_LoreFlare: /Chunks of earth violently orbit .* pelting .* with heavy debris/,
  Earth_LoreFlareDoT: /The ground trembles violently, pelting .* again/,
  Earth_GEF: /\*\* A violent explosion of frenetic energy rumbles from .*/,
  Elven_SpellBarrier: /bob.bob.bob/,
  Elven_SpellAlacrity: /bob.bob.bob/,
  Energy_Weapon: /A beam of .* energy emits from the tip of your .* and collides with .*/,
  Ensorcell_Health: /You feel healed/,
  Ensorcell_Mana: /You feel empowered/,
  Ensorcell_Spirit: /You feel rejuvenated/,
  Ensorcell_Stamina: /You feel reinvigorated/,
  Ensorcell_AS_CS: /You feel energized/,
  Ethereal_Armor: /ethereal chains encase your body against/,
  Fire_Flare: /\*\* Your .* flares? with a burst of flame! \*\*/,
  Fire_LoreFlare: /A blazing inferno erupts around .* scorching everything in its wake/,
  Fire_LoreFlareDoT: /The inferno blazing around .* ignites anew/,
  Fire_GEF: /\*\* Burning orbs of pure flame burst from .*/,
  Firewheel: /Your .* emits a fist-sized ball of lightning-suffused flames/,
  ForestArmor_WindGust: /A spiraling funnel of air bursts from your/,
  ForestArmor_LeafSwirl: /Diamond-shaped leaves sprout from your/,
  ForestArmor_MudSling: /A thick clump of mud catapults from your/,
  ForestArmor_WoodlandEmpathy: /you suddenly have a clearer understanding of nature/,
  Ghezyte: /Cords of plasma-veined grey mist seep from your/,
  Grapple_Flare: /\*\* Your .* releases? a twisted tendril of force! \*\*/,
  Greater_Rhimar: /A suffusion of frost flashes down the length of .* as a tongue of snow and ice lashes at .*|From somewhere nearby, a snowball comes whizzing towards .*, splattering as it connects/,
  GuidingLight_2ndFlare: /Your .* sprays? with a burst of plasma energy!/,
  Holy_Fire: /\*\* Your .* bursts alight with leaping tongues of holy fire/,
  Iasha: /As you attack, the baneful white flames surrounding your .* flare off and strike, bathing .* in fiery death|A peal of thunder cracks from your .* as baneful white light streams forth to surround .*, assaulting .* with flames of white-hot fury|As your .* connects with .*, baneful white flames stream off .* and strike, leaving smoking, ragged burns behind|As you land your blow, the flames surrounding the .* begin to swirl and burn and set .* alight|Baneful white flames dance from your .* as an unseen wind fans them into a raging conflaguration that assault .*/,
  Ice_GEF: /\*\* A vortex of razor-sharp ice gusts? from .*/,
  Impact_Flare: /\*\* Your .* releases? a blast of vibrating energy! \*\*/,
  Knockout: /Your .* bounce off the head of .*, causing .* to reassess the situation for a moment while standing still|A solid strike from your .* to the temple causes .* to stumble|You land a vicious blow to the head of .*|your .* bounce off the head of .* causing it to|bringing your .* down across the head of .* with a sickening thud|You feint left, then right, then crack .* across the head|cracks? the .* on the back of the head|Your .* thump .* in the head.  .* stumbles around for a moment desperate to keep .* balance but in the end .* fails miserably, and collapses to the floor in a heap, looking dazed|then reverse direction and crack|Your .* plow right into the forehead of/,
  Lathonian: /your .* suddenly begins to glow with a polychromatic light/,
  Lightning_GEF: /\*\* A vicious torrent of crackling lightning surges from .*/,
  Lightning_Flare: /\*\* Your .* emits? a searing bolt of lightning! \*\*/,
  Low_Steel: /Your .* unleashes? a blast of psychic energy/,
  Low_Steel_LoreFlareDoT: /convulses in horrified agony/,
  Magma_Flare: /\*\* Your .* expels? a glob of molten magma! \*\*/,
  ManaArmor_ManaFlares: /from your .* and you feel .* mana surge into you/,
  ManaArmor_ManaShield: /latticework springs up from the surface of your .* and shields you from some of the damage/,
  Mana_Flare: /Your .* pulses with a white-blue light!/,
  Necromancy_LoreFlare: /\*\* A sickly green aura radiates from/,
  Necromancy_LoreFlareDoT: /Small pieces of flesh rot off a/,
  Nerve: /Several thin, fibrous .* filaments erupt from your/,
  Plasma_Flare: /\*\* Your .* pulses? with a burst of plasma energy! \*\*/,
  Parasitic_Appendages: /A series of .* lash out from your .* at .*/,
  Parasitic_BloodMatch: /A cascade of needle-like appendages puncture your flesh beneath your .* as you are suddenly healed!/,
  Parasitic_Bulwark: /Your .* glisten as a sudden rush of blood spills across its surface, creating a magical bulwark against/,
  Parasitic_Defense: /Several .* reinforce your .* to defend you against the incoming attack/,
  Parasitic_BloodFlares: /You wince as .* draws upon your blood as it strikes/,
  CoraesineRelic: /\*\* The coraesine relic on your/,
  Religion_LoreFlare: /Divine flames kindle around .* leaping forth to engulf/,
  Religion_LoreFlareDoT: /The sacred inferno surrounding .* ignites anew/,
  Rusalkan: /Exploding in a tumbling current of frothy foam, a wave of sea water suddenly materializes at the call of your/,
  SigilStaff: /twining into an echo of your last spell/,
  Sigil_of_Binding: /A bolt of energy leaps from your .* within bands of concentric geometry/,
  Somnis: /For a split second, the striations of your .* expand into a sinuous pearlescent mist that rushes towards the/,
  SonicWeapon_1stFlare: /Your .* unleashes? a blast of sonic energy at/,
  SonicWeapon_2ndFlare: /With a loud snap, a blast of energy bursts from your .*/,
  Spore: /Nebulous .* tendrils curl from your .*, enswathing .* in a shroud spangled with .* spores/,
  Spritely_Intervention: /You feel yourself being pulled upright as an .* barrier appears in front of you/,
  Spritely_Maneuvering: /The .* sprite on your shoulder projects a .* barrier, shielding you/,
  Sprite_DefensiveFlares: /The .* sprite on your shoulder projects a .* barrier in front of you/,
  Sprite_Flares: /You feel a slight sting as the sprite draws upon your power to attack/,
  Steam_Flare: /\*\* Your .* erupts? with a plume of steam! \*\*/,
  Steam_GEF: /\*\* A howling gale of steaming air rushes from/,
  Summoning_LoreFlare: /A radiant mist surrounds .* unfurling into a whip of plasma/,
  Summoning_LoreFlareDoT: /The whip of plasma continues to wreathe/,
  Telepathy_LoreFlare: /Rippling and half-seen, strands of psychic power unravel from the/,
  Telepathy_LoreFlareDoT: /Locked in mental durance, .* is assailed by some unseen attack!/,
  TwinWeapon: /The buildup of .* energy surrounding .* explodes/,
  TwistedArmor_Retaliation: /The .* pulses brightly as it emits .* that surges toward/,
  TwistedArmor_Augmentation: /The scintillating glow emanating from .* on your .* shimmers and intensifies as a pulse of energy surges around you, briefly coalescing into/,
  Unbalance_Flare: /\*\* Your .* unleashes? an invisible burst of force! \*\*/,
  Vacuum_Flare: /folds? inward and draws its surroundings closer!/,
  Valence_LashofLoraetyr: /Several archaic sigils flash briefly along your .* and you begin to grow translucent, shifting in and out of view as gnarled ethereal vines erupt from your body and lash out at .*, each one solidifying before they strike/,
  Valence_SliceofShientyr: /A coil of spectral .* energy bursts? out of thin air|A coil of ghostly .* energy bursts? out of thin air|A coil of eerie .* energy bursts? out of thin air|A coil of celestial .* energy bursts? out of thin air/,
  Vethinye: /As a resonating song emanates? from your .*, it entwines you in night blue wisps of ephemera/,
  Void_GEF: /\*\* A nebulous dome of violet energy discharges? from .*/,
  VolnArmor_DSFlare: /Your .* hums with spiritual force, filling you with a sense of divine vigilance and a preternatural awareness of/,
  Water_Flare: /\*\* Your .* shoots? a blast of water! \*\*/,
  Water_LoreFlare: /A watery deluge erupts? violently around .* crushing/,
  Water_LoreFlareDoT: /The water surrounding .* churns anew/,
  Xazkruvrixis: /The life drains? visibly away from .*, as/,
  FA_1706: /The flaming aura surrounding you lashes out at .*!/,
  Battle_Standard: /With a sonorous knell, .* overtakes|With a deafening crack of thunder, .* spears .*|Cruel, glittering flames .* erupt around .*|Brazen and implacable, .* crashes down upon .*|Threads of glistening silk .* wind around .*/
}
