=begin
  This file is required in order for flaretracker_2.lic to function.

  1.0.0 (2024-09-7)
    - Initial release of flare patterns global constants.
    - 88 different flare patterns added.
  1.1.0 (2024-09-8)
    - Added lots of new flares to track, mainly armor scripts.
	- Separated non-damaging flares into a separate global constant.
  1.2.0 (2024-09-11)
	- Added all custom fatal afflares messaging.
  1.3.0 (2024-09-26)
	- Excluded Symbol of Dreams conflict with Ensorcell_Spirit.
	- Add Holy Water Flare tracking.
	- Added lots of tracking for just about every spell with a native effect or spell with a lore benefit effect that functions similar to a flare.
=end

# Define FLARE_PATTERNS as a constant to be used globally
NODMGFLARE_PATTERNS = {
  # Non-damaging flares
  Xazkruvrixis: /Your xazkruvrixis .*? emits an ominous black-green glow/,
  Wither_LoreBenefit: /A nebulous haze shimmers into view around .*?, plunging inward in a dizzying spiral to envelop .*? completely/,
  WallofThorns_Poison: /One of the vines surrounding you lashes out at/,
  WallofThorns_Block: /The thorny barrier surrounding you blocks the attack from/,
  VolnArmor_DSFlare: /Your .*? hums with spiritual force, filling you with a sense of divine vigilance and a preternatural awareness of/,
  VialFlare: /spits .*? vial out and onto the ground where it lands with a crystalline \*TINKLE\*./,
  Untrammel_LoreBenefit: /you shifts abruptly, taking on an opalescent sheen that resists the web/,
  TwistedArmor_Augmentation: /The scintillating glow emanating from .*? on your .*? shimmers and intensifies as a pulse of energy surges around you, briefly coalescing into/,
  TrollHeart: /The .*? inside the necklace beats madly for a second as it pumps lifegiving blood back into your bloodstream, revitalizing you with its regenerative blood/,
  TrollsBlood_StunBreak: /Though you are stunned and reeling, you become aware of your pounding heart.  With each beat, it grows louder and louder, faster and faster, until, with a sudden surge of strength, you throw off your stunned state!/,
  TotemAnimalistic: /flows from it and over your exposed skin, imbuing a sudden rush of power from/,
  TotemBestial: /the semitransparent figure moving to try to shield you from the attack/,
  TotemShifting: /the motes encasing your arm in incandescence as a rush of power sinks into you to strengthen your attack/,
  TotemFeral: /your vision briefly obscured with a bloody haze as a rush of strength surges into your limbs/,
  Tome_Spellwarden: /As you stare at the words, you feel the weight of tactical knowledge build in you, allowing you to better protect yourself/,
  ThurfelsWard_LoreBenefit: /bob/,
  Terror_Flare: /Your .*? releases a distorted black shadow at|A wave of wicked power surges forth from your/,
  TemporalReversion: /Your surroundings melt away as the air around you shivers with a large flux of mana. Abruptly, time wrenches violently to give you a second chance. This time, you're better prepared/,
  TemplarsVerdict_Zealot: /Your surroundings take on a violet sheen as you burn with zealous fervor/,
  Sprite_DefensiveFlares: /The .*? sprite on your shoulder projects a .*? barrier in front of you/,
  Spritely_Maneuvering: /The .*? sprite on your shoulder projects a .*? barrier, shielding you/,
  Spritely_Intervention: /You feel yourself being pulled upright as an .*? barrier appears in front of you/,
  SpiritStrike_LoreBenefit: /The invisible force draws back to guide you once more/,
  SpiWardingII_LoreBenefit: /Starburst patterns of pale blue light sweep forward from your chest and infuses the deep blue glow with its energy/,
  SoulWard: /The evanescent shield shrouding you flares to life/,
  Somnis: /For a split second, the striations of your .*? expand into a sinuous pearlescent mist that rushes towards the/,
  SigilStaff_DoubleCast: /twining into an echo of your last spell/,
  Sigil_of_Binding: /A bolt of energy leaps from your .*? within bands of concentric geometry/,
  ShieldCape_Block: /forms a shield in front of you that turns solid enough to block .*? incoming blow/,
  Rusalkan: /Exploding in a tumbling current of frothy foam, a wave of sea water suddenly materializes at the call of your/,
  RangerTrinket_Resistance: /pulses briefly, deflecting some/,
  RangerTrinket_ManaAbsorb: /The .*? essence is drawn toward your/,
  RapidFire_NoCooldown: /Moisture beads on the surface of your skin then evaporates away, taking with it your recent elemental fatigue/,
  RapidFire_Channel: /Seeing an opportunity, you accelerate time and empower your spell/,
  Parasitic_BloodMatch: /A cascade of needle-like appendages puncture your flesh beneath your .*? as you are suddenly healed\!/,
  Parasitic_Bulwark: /Your .*? glisten as a sudden rush of blood spills across its surface, creating a magical bulwark against/,
  Parasitic_Defense: /Several .*? reinforce your .*? to defend you against the incoming attack/,
  NightshroudCloak_Hide: /a cyclone of shadows emerge from your .*?.  The shadows swirl around in an attempt to conceal you/,
  NaturesTouch_ArcaneReflex: /Vital energy infuses you, hastening your arcane reflexes/,
  NaturesTouch_PhysicalProwess: /The vitality of nature bestows you with a burst of strength/,
  MinorFire_Ignite: /Some of the flames from the stream of fire linger around .*?/,
  MechanizedArm_Block: /Just as .*? attacks, your arm suddenly swings out and intercepts it!/,
  ManaArmor_ManaShield: /latticework springs up from the surface of your .*? and shields you from some of the damage/,
  ManaArmor_ManaFlares: /radiates from your .*? and you feel .*? mana surge into you\!| returning to you with an audible \*WHOOSH\*/,
  MageArmor_Water: /The raw elemental energy surrounding you takes on a watery look as it/,
  MageArmor_Fire: /The fiery torrent of energy surrounding you flares toward/,
  MageArmor_Earth: /The energy surrounding you condenses into hard stone/,
  LuckTalisman_Offensive: /You hear the soft tinkle of rolling dice, followed by the sound of coins dropping/,
  LuckTalisman_Defensive: /You hear the soft tinkle of rolling dice, followed by a faint lucky feeling/,
  Lathonian: /your .*? suddenly begins to glow with a polychromatic light/,
  KroderineChains: /Your kroderine chains rapidly consume the magical power of the attack/,
  Kroderine: /Your .*? cast. The magic of the spell is instantly devoured by the/,
  GlovesofTonis: /A forceful squall suddenly shoots through your .*?, drawing your movements along their intended path/,
  Ghezyte: /Cords of plasma-veined grey mist seep from your/,
  ForestArmor_WindGust: /A spiraling funnel of air bursts from your/,
  ForestArmor_LeafSwirl: /Diamond-shaped leaves sprout from your/,
  ForestArmor_MudSling: /A thick clump of mud catapults from your/,
  ForestArmor_WoodlandEmpathy: /you suddenly have a clearer understanding of nature/,
  Fasthrs_Reward: /The dull golden nimbus surrounding you flares into life as it glows brightly for a moment/,
  Ethereal_Armor: /ethereal chains encase your body against/,
  EonakArm_Block: /your arm suddenly swings out and intercepts it/,
  Ensorcell_Health: /You feel healed/,
  Ensorcell_Mana: /You feel empowered/,
  Ensorcell_Spirit: /You feel rejuvenated/,
  Ensorcell_Stamina: /You feel reinvigorated/,
  Ensorcell_AS_CS: /You feel energized/,
  Elven_SpellBarrier: /Strands of translucent mana swirl about you, creating a protective barrier/,
  Elven_SpellAlacrity: /Your .*? flares with a pale light/,
  ElementalDefenderRing: /The .*? on your .*? flares brightly as it absorbs the .*?/,
  EleTargeting_LoreBenefit: /elemental energy energizes you/,
  ElemDeflection_LoreBenefit: /A shimmering field of energy flashes around you, reflecting/,
  EleDefIII_LoreBenefit: /A heavy barrier of stone momentarily forms around you/,
  EleBias_LoreBenefit: /Your magical awareness grows more acute for an instant/,
  EleBarrier_LoreBenefit: /Your skin hardens for a moment and softens/,
  Dramatic_Drapery_Wondorous: /Branching filaments of power snap outward from your/,
  Dramatic_Drapery_Masquerade: /distorts the air around you, confounding an/,
  Dragonclaw_Flare: /As you strike, a deep golden light surrounds your/,
  Death_Flare: /Your .*? emits an ominous black-green glow/,
  CursedArmor_Calm: /as your vision burns with hypnotic resolve/,
  CursedArmor_DS_TD: /Dark tendrils lash out from your .*? and form a crimson-runed shroud of darkness around you/,
  CursedArmor_AS_CS: /Dark tendrils lash out from your .*? and invigorate your resolve/,
  Bubble: /high-pitched sound and causes your skin and muscles to/,
  Breeze_Tailwind: /A favorable tailwind springs up behind you/,
  Breeze_Offensive: /is buffeted by a burst of wind and pushed back|is buffeted by a sudden gust of wind/,
  Brace_Parry: /Using the bone plates surrounding your forearms, you parry the attack/,
  Brace_Disarm: /strikes one of the bony protrusions on your forearms and it is wrenched out of/,
  BootsofTonis: /you, a swirling whirlwind bursts into life around your form. Time seems to slow to a crawl as the turbulent winds guide your movements, allowing you to avoid the assault/,
  BoneShatter_LoreBenefit: /The internal skeletal structure of .*? implodes inward upon itself/,
  Blink_1215: /You find yourself moved several feet from your original position/,
  Blink: /Your .*? suddenly lights? up with hundreds of tiny blue sparks/,
  Benediction_LoreBenefit: /Pearly light flares up suddenly from within you, lending strength and focus to your attack/,
  Barkskin: /The layer of bark on you hardens and absorbs/,
  Banshee: /emits a deafening wail as a bright red glow erupts from its surface, surrounding you/,
  BalanceFrenzy_Flare: /The .*? flashes a shade of scarlet|The .*? flashes a shade of viridian/,
  BalanceFrenzy_DoubleFlare: /The .*? is suddenly engulfed in scarlet light|The .*? is suddenly engulfed in viridian light/,
  AstralSpear_Dispel: /With an opaline flare, the nacreous spear passes through .*? , disrupting the veil of wards surrounding/,
  Animalistic_InstinctFlares: /up from the point of impact, spreading over the chest of your/,
  Aganjira: /Mana cascades across your .*?, causing the fabric to shiver against your skin as it draws the scattered power into it and transforms it into mana/,
  Adamantine: /the incredibly hard surface of your adamantine/,
  Acuity_Flare: /Your .*? glows intensely with a verdant light\!|form before shifting its focus toward you, setting your .*? aflame for a brief momen/
}

DMGFLARE_PATTERNS = {
  # Damaging flares
  Acid_Flare: /\*\* Your .*? releases? a spray of acid\! \*\*|Luminescent green droplets dribble from your .*? and puddle mid-air, creating a large globule of sizzling liquid that bursts over|Without warning, an ominous cloud forms overhead and churns violently, raining blistering droplets of acid down upon .*? until the fog is sucked into your/,
  Air_Flare: /\*\* Your .*? unleashes? a blast of air\! \*\*|Your ears pop as the air pressure suddenly drops, and a fierce tornado coalesces around .*?, spinning .*? violently in the air for a brief moment before the winds die down/,
  Air_LoreFlare: /A fierce whirlwind erupts? around .*? encircling .*? in a suffocating cyclone/,
  Air_LoreFlareDoT: /The cyclone whirls around .*? anew/,
  Air_GEF: /\*\* A howling gale of steaming air rushes from .*?/,
  Animalistic_FuryFlares: /slender tendrils rising up to coalesce into the ethereal form of/,
  Balefire_DemonAttack: /shudders slightly as chaotic energy is drawn from its form and fused with the attack/,
  Briar: /Vines of vicious briars whip out from your/,
  ChainSpear: /The .*? head of your .*? catches across .*?/,
  ChronomageDagger: /Taking a chance you hurl .*? at .*? again and suddenly everything returns to normal speed as time catches up with itself/,
  CloakofShadows_Retribution: /A dark shadowy tendril rises up from your skin/,
  Cold_Flare: /\*\* Your .*? glows? intensely with a cold blue light\! \*\*|A thin stream of icy cold liquid shoots forth from your/,
  Cold_GEF: /\*\* A vortex of razor-sharp ice gusts from .*? and coalesces? around a .*?\! \*\*/,
#  Coraesine_Old: /Coraesine_Old/,
  Coraesine_Pure: /A massive vortex of shrapnel-laden air coalesces around|You feel the .*? respond to your will, and suddenly it flares up with a blazing white-grey aura\! Vicious winds curl around you in a spiraling vortex, increasing your momentum as you let loose a lightning-quick strike/,
  CoraesineRelic: /\*\* The coraesine relic on your/,
  Disintegration_Flare: /\*\* Your .*? releases? a shimmering beam of disintegration\! \*\*|Momentarily illuminated by a nefarious veil of light that emanates from your/,
  Dispel_Disruption: /\*\* Your .*? glows? brightly for a moment, consuming the magical energies around .*?\!|Afterimages of your .*? manifest around/,
  Dispel_FluxCrit: /fluxes chaotically/,
  Disruption_Flare: /\*\* Your .*? releases? a quivering wave of disruption\! \*\*|An unnatural shift in atmospheric pressure causes intense and harsh bursts of air that yield a violent, resonant attack on/,
  Earth_LoreFlare: /Chunks of earth violently orbit .*? pelting .*? with heavy debris/,
  Earth_LoreFlareDoT: /The ground trembles violently, pelting .*? again/,
  Earth_GEF: /\*\* A violent explosion of frenetic energy rumbles from .*?/,
  Energy_Weapon: /A beam of .*? energy emits from the tip of your .*? and collides with .*?/,
  Fire_Flare: /\*\* Your .*? flares? with a burst of flame\! \*\*|Emerging from your .*?, a massive ball of flames coalesces and launches straight toward|Flames form like deep scarlet-orange ribbons around your/,
  Fire_LoreFlare: /A blazing inferno erupts around .*? scorching everything in its wake/,
  Fire_LoreFlareDoT: /The inferno blazing around .*? ignites anew/,
  Fire_GEF: /\*\* Burning orbs of pure flame burst from .*?/,
  Firewheel: /Your .*? emits a fist-sized ball of lightning-suffused flames/,
  GlobusElanthias: /Rising from the .*? that is wedged into your .*?/,
  GlobusNaidem: /Lashing out from your .*?, .*? extends one hand and rakes a claw across .*? flesh|Boils on .*? skin grow overly full and eventually burst, causing pus to leak from the new wound/,
  Grapple_Flare: /Your .*? releases? a twisted tendril of force|Catapulting from your .*?, a thick, braided rope twists and twines around/,
  GreaterBlackOra: /A low moaning emanates from your .*? as the shadows swirl off and surround .*?, assaulting it with flashes of greenish-black essence|As you attack .*?, the shadows surrounding your .*? swirl off and strike|As you land your blow, the shadows surrounding .*? begin to swirl like a miniature vortex. The greenish-black essence batters .*?|As you strike .*?, the shadows surrounding .*? swirl off and strike|As your .*? connects with .*?, a low hiss is heard and the shadows strike with greenish-black essence fangs|Dancing bursts of greenish-black essence pulse from your .*? as the shadows lengthen and extend to assault .*?|The shadows surrounding your .*? lash out with a crack of greenish-black essence/,
  GreaterRhimar: /A suffusion of frost flashes down the length of .*? as a tongue of snow and ice lashes at .*?|From somewhere nearby, a snowball comes whizzing towards .*?, splattering as it connects/,
  GuidingLight_2ndFlare: /Your .*? sprays? with a burst of plasma energy/,
  HolyFire: /Your .*? bursts alight with leaping tongues of holy fire/,
  HolyWater: /Your .*? sprays? forth a shower of pure water/,
  Ice_GEF: /\*\* A vortex of razor-sharp ice gusts? from .*?/,
  Impact_Flare: /\*\* Your .*? releases? a blast of vibrating energy\! \*\*|A thunderous boom emanates from your .*? as earthen rubble and debris surges upward/,
  Knockout: /Your .*? bounce off the head of .*?, causing .*? to reassess the situation for a moment while standing still|A solid strike from your .*? to the temple causes .*? to stumble|You land a vicious blow to the head of .*?|your .*? bounce off the head of .*? causing it to|bringing your .*? down across the head of .*? with a sickening thud|You feint left, then right, then crack .*? across the head|cracks? the .*? on the back of the head|Your .*? thump .*? in the head.  .*? stumbles around for a moment desperate to keep .*? balance but in the end .*? fails miserably, and collapses to the floor in a heap, looking dazed|then reverse direction and crack|Your .*? plow right into the forehead of/,
  Lightning_GEF: /\*\* A vicious torrent of crackling lightning surges from .*?/,
  Lightning_Flare: /\*\* Your .*? emits? a searing bolt of lightning\! \*\*|Gathering around your .*?, a pulsating light grows in intensity until a shocking eruption of energized power scorches/,
  LowSteel: /Your lowsteel .*? unleashes? a blast of psychic energy/,
  LowSteel_DoT: /convulses in horrified agony/,
  Magma_Flare: /\*\* Your .*? expels? a glob of molten magma\! \*\*|Your .*? a blood red hue, and tall mounds of crimson and carmine liquid bubble up from beneath/,
  Mana_Flare: /Your .*? pulses with a white-blue light\!/,
  MindWrack_Flare: /Your .*? unleashes? a blast of psychic energy/,
  MinorAcid_Melt: /Acid continues to eat away at .*?/,
  MinorFire_Burn: /The flames around .*? continue to burn/,
  MinorShock_StunShock: /Tiny arcs of lightning briefly dance across .*? skin/,
  MinorWater_Soak: /The water completely drenches .*?/,
  NebularWeapon: /Cold as the great void, the silvery power of starlight channels through your/,
  Necromancy_LoreFlare: /\*\* A sickly green aura radiates from/,
  Necromancy_LoreFlareDoT: /Small pieces of flesh rot off a/,
  Nerve: /Several thin, fibrous .*? filaments erupt from your/,
  Pestilence_ReactiveFlare: /You exhale a virulent green mist toward/,
  Pestilence_DoT: /Pus-filled sores erupt|Boils rupture all over|skin hardens into a black rot and begins to crumble|wails as painful boils form and erupt|begins hemorrhaging from multiple orifices/,
  Plasma_Flare: /\*\* Your .*? pulses? with a burst of plasma energy\! \*\*/,
  Parasitic_BloodFlares: /You wince as .*? draws upon your blood as it strikes/,
  Religion_LoreFlare: /Divine flames kindle around .*? leaping forth to engulf/,
  Religion_LoreFlareDoT: /The sacred inferno surrounding .*? ignites anew/,
  ShieldCape_BroochFlare: /attached to the left shoulder of your .*? suddenly explodes with a brilliant flash/,
  ShadowDeathWeapon: /Ravenous tendrils of shadow burst forth from .*?, draining the very life from .*?/,
  SigilStaff_Dispel: /Tendrils of .*?? energy lash out from your .*?? toward .*?? and cage/,
  Smite_Infusion: /With a sudden burst of divine insight, you're able to amplify the power of your/,
  Smite_InstantDeath: /A minuscule blue-white star slowly ascends from the floor directly under the|A triad of ebony orbs conjoined by crackling ribbons of violet energy suddenly appear out of nowhere/,
  SolarWeapon: /Searing hot, the golden power of the sun is channeled through your/,
  SonicWeapon_1stFlare: /Your .*? unleashes? a blast of sonic energy at/,
  SonicWeapon_2ndFlare: /With a loud snap, a blast of energy bursts from your .*?/,
  Spikes: /\*\* A spike on your .*? jabs into .*?\! \*\*/,
  SpiritGauntlet: /Your bolt of energy suddenly bursts, scattering into particles|The diffuse golden particles swirl and collapse in on themselves, centered on/,
  Spore: /Nebulous .*? tendrils curl from your .*?, enswathing .*? in a shroud spangled with .*? spores/,
  Steam_Flare: /\*\* Your .*? erupts? with a plume of steam\! \*\*/,
  Steam_GEF: /\*\* A howling gale of steaming air rushes from/,
  Summoning_LoreFlare: /A radiant mist surrounds .*? unfurling into a whip of plasma/,
  Summoning_LoreFlareDoT: /The whip of plasma continues to wreathe/,
  Telepathy_LoreFlare: /Rippling and half-seen, strands of psychic power unravel from the/,
  Telepathy_LoreFlareDoT: /Locked in mental durance, .*? is assailed by some unseen attack\!/,
  Tome_Spellglider: /your .*? unleashes a dazzling arcane projectile/,
  Tome_Spellweaver: /Arcane energy streaks toward .*? and collides in a volatile clash of mana and matter/,
  Tome_Spellvault: /is buffeted by the corruscating arcane energy/,
  TwinWeapon_Detonation: /colored energy lash out from your/,
  Twisted_Flare: /\*\* A scintillating .*? glow shimmers and oscillates across your/,
  Unbalance_Flare: /\*\* Your .*? unleashes? an invisible burst of force\! \*\*|With a loud \*\*BOOM\*\* from your/,
  Vacuum_Flare: /folds? inward and draws its surroundings closer\!|Thin strands of black matter surge forth from your .*? toward/,
  Valence_LashofLoraetyr: /Several archaic sigils flash briefly along your .*? and you begin to grow translucent, shifting in and out of view as gnarled ethereal vines erupt from your body and lash out at .*?, each one solidifying before they strike/,
  Valence_SliceofShientyr: /A coil of spectral .*? energy bursts? out of thin air|A coil of ghostly .*? energy bursts? out of thin air|A coil of eerie .*? energy bursts? out of thin air|A coil of celestial .*? energy bursts? out of thin air/,
  Vethinye: /it entwines you in night blue wisps of ephemera/,
  VibrationChant_Shatter: /You focus your voice on .*? with perfect resonance, causing it to shatter into thousands of tiny pieces/,
  Void_GEF: /\*\* A nebulous dome of violet energy discharges? from .*?/,
  Water_Flare: /Your .*? shoots? a blast of water|Funneling upward, a spout of water streams from your .*? and begins to spin rapidly as it moves forward, ravaging/,
  WebbingCaughtFire: /The webbing around .*? catches fire/,
  WildEntropy_Dot: /Patches of discolored rot spread further, eating away at/,
  FA1706: /The flaming aura surrounding you lashes out at .*?\!/,
  Fervor1618: /Your .*? surges with power as .*? radiance coalesces around it/,
  EL1117_Overload: /An overload of mental energies pulse through your link/,
  BS_Reckoning: /With a deafening crack of thunder, a frayed bolt of violet-hazed lightning spears the .*?|Peals of laughter, bright and sharp, echo in your ears, transfixing the .*?|Falling like a hammer from the sky, a golden light strikes the .*? with resounding force\!|Tangled briars rise to catch the .*? on their thorns\!|Subtly tinted mists daub themselves upon the .*? , leeching away color\!|Cast in radiant outline, a massive silver fist closes tight around the .*?|Brazen and implacable, the light of judgment crashes down upon the .*?|A chill crystallizes the air, and the .*? is engulfed by a blazing, ice-bright vortex\!|Spinning rings of gem-bright color coalesce around the .*? and flare to brilliance\!|Warmth blooms at the .*?'s heart, quickly kindling into burning flame\!|Heat gathers and blossoms, bathing the .*? in the blistering brilliance of the sun\!|Darkness gathers around the .*? , speared through by pinpoints of white fire\!|The very air rips past the .*? in a gold-streaked blur, chased by an echo of wings\!|Striking swift and vicious, unseen claws rake at the .*? , and hidden teeth bite\!|Cruel, glittering flames born of darkness erupt around the .*?|Crackling and luminous, gold and silver threads of pure magic slice at the .*? with alacrity\!|Smoke drifts in languid coils, entangling the .*? in its smothering embrace\!|Glistening and dark, a soul-sucking maw manifests behind the .*? as attenuated fangs descend\!|Hissing darkness, acrid and caustic, assaults the .*? in a flurry of lashing tentacles\!|Laid open by sorrow made manifest, the .*? keens in pain\!|Night falls, bearing the .*? down beneath a crushing wave of fear\!|Harsh battle cries frenzied with bloodlust split the air and tear into the .*?|With a sonorous knell, a frigid wind overtakes the .*?|A bewildering frenzy of silver spins around the .*? in dizzying assault, moon-bright and night-dark by turns\!|A haze of golden motes envelops the .*? within its cloying embrace\!|A sinuous shimmer of violet scales slices across the .*? , bleeding crimson in its wake\!|Threads of glistening silk wind around the .*? and pull taut\!|Slithering whispers encircle the .*? in aqueous trails of silvery mist\!|With a vengeful hiss, a phantasmal arc of star-bright silver slices into the .*?|A ferocious downdraft assaults the .*? with the thunder of countless wings\!|Verdant vines enfold the .*? in their leafy embrace\!|A smothering veil of violet-sparked ash billows over the .*? , searing where it touches\!|The .*? is beset by a brilliant flurry of flashing blades\!|A liquid surge of silvery power breaks against the .*? , scattering in salty spray\!|Striking out of the darkness, unseen daggers stab at the .*? from behind\!|Motes of color swirl up around the .*? in a frenetic dance, bursting with sudden and percussive force\!|Flickering yellow and red, rebellious sparks billow up around the .*? in a blistering brume\!|Purifying white fire envelops the .*? , casting him in blackened silhouette\!|Rippling twilight envelops the .*? in banded hues of dusk and dawn\!/,
  BS_HallowedReprisal: /Fiery red barbs uncoil from the shadows nearby and lash out at/,
  BS_DivineBulwark: /.*? shield springs into being between you and your attacker to temper the blow\!/,
  FatalAfflares: /A torrent of thick crimson blood rains down upon .*?, quelling .*? form\!|Pouring from your .*?, a sinister veil of mist shrouds .*? in suffocating tendrils of obscurity\!|light project from your .*? eyes toward .*? in a brilliant blast, knocking .*?|Mighty hooves drum the .*? as a tide of spectral buffalo thunders forth, trampling .*? in its chaotic path|Spiraled rakka horns burst from the .*? and propel maliciously upward along .*? form|Scythe-shaped rolton horns burst from the .*? and slice wickedly upward, cutting along .*? form|Crimson and gold wings sprout from your .*? and flutter toward .*? before growing to a magnificent size to envelop .*? in a mighty stranglehold|Intense .*? flames radiate from your .*? and surround .*? in a powerful rage|Your .*? with primal force as bone fragments rain down upon .*?|Threads of .*? energy project outward from your .*? and slice through .*?|Crackling with fiery might, your .*? a searing volley of fireballs that soar like meteors toward .*? and explode on contact|Your .*? a series of pulsating, blinding lights that scorch and sear .*?, a pungent odor of burning flesh lingering in the air|Strands of viscous white webbing covered with hundreds of black widow spiderlings spurt forth from your .*? and envelop .*? in a strangling constraint|With a bloodthirsty howl, a snarled and hideous jackal lunges forth from your .*? and rips ruthlessly at .*? with its powerful fangs|An ominous buzzing emanates from your .*? as a calamitous swarm of giant hornets besieges .*? with their torturous stingers|Materializing above, two enormous, clenched fists slam down forcefully upon .*? with brutal strength|Thorny vines and mold-infested roots emerge from the .*? beneath .*?, winding viciously around .*? with destructive results|Cracked and splintered bones propel rapidly from your .*? and strike .*? in a merciless onslaught|A thick, yellowish fog engulfs .*?, causing tiny pustules to form and burst into thousands of flesh-hungry botflies|Slick viridian snakes wriggle from the end of your .*? and slither along the .*? to .*?, where they unleash a brutal, venomous assault|Hundreds of razor-sharp daggers discharge from your .*? in a virulent barrage to mutilate .*?|Materializing in thin air, a thick, rusty iron collar forms around .*? and clamps shut, constricting all air flow|Waves of luminous energy pour from your .*? and assault .*? with a ruthless barrage of arduous strikes|An intense rush of energy spews from your .*? and engulfs .*? with an unrelenting dynamic attack|Your .*? a blizzard's wrath\!  Ice shards and snowflakes converge to engulf .*? in a relentless storm of freezing fury|Your .*? with airy energy, sculpting zephyrs into a symphony of cyclonic tempests that whips violently around .*?|Bursting from your .*?, a thick, flour-like cloud forms above .*? and splits open to drop a barrage of petrified biscuits onto .*? that disintegrates after impact|Giant claws unfurl from your .*? and scratch viciously at .*?, mauling .*? with unbridled furor|Luminescent motes of .*? eject from your .*? and propel toward .*? with increasing speed, finally bursting in a blinding flash|Your .*? rhythmically as a cacophony of ear splitting sounds assaults .*? from all directions|Dust particles swirl intensely and coalesce to form an elongated, open-mouthed macabre face that discharges a deafening, ear piercing wail directly at .*?|Reaching outward from your .*?, a ghastly pair of spectral hands grabs and claws ferociously at .*?|A miniscule orb of light floats from your .*?, hovering mid-air and gradually expanding to become a ghostly likeness of you\!  With a savage howl, the shadowy image unleashes a mighty attack on .*?|For a brief moment, your .*? in and out of existence, an enormous spectral skull appearing long enough to open its immense mouth and chomp down upon .*?|Flailing and spinning wildly, a whirlwind of tiny whips bursts from your .*? and violates .*? with a brutal slashing assault|Thin blades of grass fall from your .*? as a spectral doe appears in front of .*?, hind legs kicking and flailing in a protective whirlwind attack|a slit-pupiled eye bursts from your .*? and issues a chilling, intimidating stare directly at .*?|Black sparks emanate from your .*? as a silver-edged black sword appears and begins to repeatedly slash at .*?|Sparks of deep blue shimmer into existence from your .*? as an emerald trident appears and begins to repeatedly stab at .*?|With a loud cracking noise, tiny eggs spill forth from your .*? onto the .*? and erupt, birthing miniature roltons that begin to gnash viciously at .*? with their curved incisors before disappearing|With a loud cracking noise, tiny eggs spill forth from your .*? onto the .*? and erupt, birthing a cluster of rattlesnakes that repeatedly lash out and bite .*? with razor-sharp fangs|Gangly black tentacles sprout upward from the .*? and wrap around .*?, constricting .*? with brutal force|As brilliant as the sun, radiant beams surge forth from your .*? and burn .*?, leaving a stench of scorched matter in the air|A cacophony of sound blares from your .*?, surrounding .*? in a barrage of confounding noise|With a loud cracking noise, translucent eggs spill forth from your .*? onto the .*? and erupt, birthing albino tomb spiders that begin to devour .*? viciously with their glistening fangs before disappearing|Green sparks seep from your .*? and diverge through the air as a grey sickle appears and begins to hack and slash viciously at .*?|Thick, smoky wisps of jade ooze sinuously from your .*? and entwine around .*? in a strangling embrace/
}

# Define ATTACK_PATTERNS as a constant to be used globally
ATTACK_PATTERNS = {
  Attack: /You (?:swing a|thrust with|slash with|hurl a|fire a)|You take aim and|You attempt to(?:jab|punch|grapple|kick)|You make a precise attempt to(?:jab|punch|grapple|kick)|You gesture at|You connect|Your .*? connects|You lunge forward|In a fluid whirl, you sweep your/i
}
