name: Run repo mirror
on:
  schedule:
    - cron: '42 */3 * * *'
  push: []

jobs:
  mirror:
    if: "!contains(github.event.head_commit.message, 'Script updates within last')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'

      - name: Install sqlite3 gem
        run: gem install sqlite3

      - name: Run mirror script
        run: ruby mirror_runner.rb
        env:
          CHARACTER_CONNECTION_STRINGS: ${{ secrets.CHARACTER_CONNECTION_STRINGS }}
          CADENCE: ${{ secrets.CADENCE }}

      - name: Remove scripts set to be skipped
        run: rm -v lib/$(grep .lic skip_list) || true

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lib
          (git status --porcelain | wc -l | grep 0 > /dev/null) || git commit -m "Script updates within last 3 hours"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
