name: Run repo mirror
on:
  schedule:
    - cron: '42 */3 * * *'
  push: []

jobs:
  mirror:
    if: "!contains(github.event.head_commit.message, 'Script updates within last')"
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: run mirror script
        run: bundle exec ruby lichless_repo/lichless_repo.rb
        timeout-minutes: 2
        continue-on-error: true
        env:
          CADENCE: ${{ secrets.CADENCE }}

      - name: run mirror script - Dragonrealms
        run: bundle exec ruby lichless_repo/lichless_repo.rb
        timeout-minutes: 2
        continue-on-error: true
        env:
          CADENCE: ${{ secrets.CADENCE }}
          MIRROR_DR: true

      - name: Remove any scripts maintained by EO already in other jinx repos
        run: bash sync_eol.sh

      - name: Remove scripts set to be skipped
        run: grep .lic skip_list | while read script;do rm lib/${script} || true;done

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lib
          git add dragonrealms/lib
          git add gs_map/gs_map.json
          if (git status --porcelain | wc -l | grep 0 > /dev/null);then echo "No changes to commit";else git commit -m "Script updates within last 3 hours";fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
